name: moviedb
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  rxdart: ^0.27.3
  http: ^1.1.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  isar: *isar_version
  isar_flutter_libs: *isar_version
  auto_animated_list: ^1.0.4
  great_list_view: ^0.2.3  
  page_transition: ^2.1.0
  flutter_native_splash: ^2.3.4
  connectivity_plus: ^5.0.2
  flutter_spinkit: ^5.2.0
  animate_do: ^3.1.2
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  mockito: ^5.4.4
  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  isar_generator: *isar_version
  flutter_launcher_icons: ^0.13.1
  bootstrap_icons: ^1.11.3
  animations: ^2.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/fonts/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      